language: php

matrix:
  include:
    - php: 5.6
      env: DEPENDENCIES='low'
    - php: 5.6
    - php: hhvm
    - php: 7.0
    - php: 7.0
      env: DEPENDENCIES='dev'
  fast_finish: true

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - php vendor/phpspec/phpspec/bin/phpspec run -f dot
